### ISSUE TITLE
Predicted value included NaN

### ISSUE THREAD

**Issue by ckj18** [Vul-LMGNN/vul-LMGGNN#6]
I encountered an issue while reproducing your project. I understand that in the BertGGCN class, the output value x of conv is the probability value from the softmax, and cls_logit is the binary output logit from codebert. When summing these two according to Equation 11 from the paper, since cls_logit can contain negative values, taking the log when there are negative values in pred results in NaN values. Am I the only one experiencing this issue?

**Comment by aikedaerC** [comment]
me too

**Comment by aikedaerC** [comment]
> I encountered an issue while reproducing your project. I understand that in the BertGGCN class, the output value x of conv is the probability value from the softmax, and cls_logit is the binary output logit from codebert. When summing these two according to Equation 11 from the paper, since cls_logit can contain negative values, taking the log when there are negative values in pred results in NaN values. Am I the only one experiencing this issue?

me too, bro

**Comment by vinzcamp8** [comment]
Me too. As a consequence I removed the log operation. Also using leaky_relu instead of relu seems to have better performance.

**Comment by Abdelrahman-405** [comment]
> Me too. As a consequence I removed the log operation. Also using leaky_relu instead of relu seems to have better performance.

Pls can you help me to run this project 🙏

**Comment by vinzcamp8** [comment]
> > Me too. As a consequence I removed the log operation. Also using leaky_relu instead of relu seems to have better performance.
> 
> Pls can you help me to run this project 🙏

Yeah you can [follow my fork at gpu branch](https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu), I'm doing a comparisons using this and others model as well.

**Comment by Abdelrahman-405** [comment]
Could you please provide me with you contact info 🙏 @vinzcamp8

**Comment by Abdelrahman-405** [comment]
> > > أنا أيضًا. ونتيجة لذلك، قمت بإزالة عملية السجل. ويبدو أيضًا أن استخدام leaky_relu بدلاً من relu يؤدي إلى أداء أفضل.
> > 
> > 
> > من فضلك هل يمكنك مساعدتي في تشغيل هذا المشروع 🙏
> 
> نعم يمكنك [متابعة شوكة بلدي في فرع وحدة معالجة الرسومات](https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu) ، وأنا أقوم بإجراء المقارنات باستخدام هذا النموذج والنماذج الأخرى كذلك.

Could you please provide me with you contact info i@vinzcamp8

**Comment by Abdelrahman-405** [comment]
> > > Me too. As a consequence I removed the log operation. Also using leaky_relu instead of relu seems to have better performance.
> > 
> > 
> > Pls can you help me to run this project 🙏
> 
> Yeah you can [follow my fork at gpu branch](https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu), I'm doing a comparisons using this and others model as well.

Im sorry put i still need some help because im still beginner if you can help me to run this project or give me a road map to run this project 🙏

**Comment by LYY-599** [comment]
> > > Me too. As a consequence I removed the log operation. Also using leaky_relu instead of relu seems to have better performance.
> > 
> > 
> > Pls can you help me to run this project 🙏
> 
> Yeah you can [follow my fork at gpu branch](https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu), I'm doing a comparisons using this and others model as well.

I have encountered this problem. May I ask how to solve it
Traceback (most recent call last):
  File "run.py", line 254, in <module>
    accuracy, precision, recall, f1 = test(model_test, DEVICE, test_loader)
  File "/public/home/luyuanying2023/lyy/vul-LMGGNN-main/test.py", line 61, in test
    fpr, tpr, _ = roc_curve(y_true, y_probs)
  File "/public/home/luyuanying2023/anaconda3/envs/LMG/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 770, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
  File "/public/home/luyuanying2023/anaconda3/envs/LMG/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 538, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "/public/home/luyuanying2023/anaconda3/envs/LMG/lib/python3.8/site-packages/sklearn/utils/validation.py", line 208, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File "/public/home/luyuanying2023/anaconda3/envs/LMG/lib/python3.8/site-packages/sklearn/utils/validation.py", line 208, in <listcomp>
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File "/public/home/luyuanying2023/anaconda3/envs/LMG/lib/python3.8/site-packages/sklearn/utils/validation.py", line 151, in _num_samples
    raise TypeError("Singleton array %r cannot be considered"
TypeError: Singleton array 0 cannot be considered a valid collection.

**Comment by vinzcamp8** [comment]
Give a shot to [my fork at gpu branch](https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu). It is the latest refactored code that I have done on that project.

**Comment by huangyuyan3** [comment]
Could the 24G GPU run the code you have restructured?

**Comment by vinzcamp8** [comment]
Yes

**Comment by huangyuyan3** [comment]
thanks!!

> Yes
> […](#)
>

**Comment by huangyuyan3** [comment]
> Yes
> […](#)

Sorry, may I ask how the concept of "knowledge distillation" is specifically manifested? I'm a beginner and haven't found this part of the content about "knowledge distillation". I'm very sorry.

**Comment by vinzcamp8** [comment]
That part is from the original project, not from my fork, so refer to the
original authors... Anyway I have not studied that concept during my
work, sorry!

Il giorno mar 16 set 2025 alle ore 13:32 huangyuyan3 <
***@***.***> ha scritto:

**Comment by huangyuyan3** [comment]
> That part is from the original project, not from my fork, so refer to the
> original authors... Anyway I have not studied that concept during my
> work, sorry!
> 
> Il giorno mar 16 set 2025 alle ore 13:32 huangyuyan3 <
> ***@***.***> ha scritto:
> […](#)

OK, in any case, thank you!!!

**Comment by huangyuyan3** [comment]
> That part is from the original project, not from my fork, so refer to the
> original authors... Anyway I have not studied that concept during my
> work, sorry!
> 
> Il giorno mar 16 set 2025 alle ore 13:32 huangyuyan3 <
> ***@***.***> ha scritto:
> […](#)
I'm very sorry to bother you again, but I really don't know what to do. Would you mind answering this question? Every epoch during the training, does CodeBERT perform the embedding for all the nodes, and is CodeBERT also involved in the training process?Or does CodeBERT only perform embedding on the entire code sequence? I noticed that the logic you reproduced is different from that of the original author. If I use CodeBERT to embed all the nodes in each epoch, the process will take an extremely long time, possibly even several days.Moreover, it will cause OOM.

**Comment by vinzcamp8** [comment]
Hi I'm sorry but I do not remember the entire work, I left it 9 months ago...
Be sure you are using the codebase inside the gpu branch https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu
I just found this note in my cloud drive:
[Thesis project.pdf.pdf](https://github.com/user-attachments/files/22534172/Thesis.project.pdf.pdf)

That's all, good luck :)

**Comment by huangyuyan3** [comment]
> Hi I'm sorry but I do not remember the entire work, I left it 9 months ago... Be sure you are using the codebase inside the gpu branch https://github.com/vinzcamp8/vul-LMGGNN/tree/gpu I just found this note in my cloud drive: [Thesis project.pdf.pdf](https://github.com/user-attachments/files/22534172/Thesis.project.pdf.pdf)
> 
> That's all, good luck :)

Thank you very, very, very, very much!
